allow:
  - name: actions/cache
    tag: "v4"
  - name: actions/checkout
    tag: "v4"
  - name: actions/download-artifact
    tag: "v4"
  - name: actions/setup-go
    tag: "v5"
  - name: actions/setup-python
    tag: "v5"
  - name: actions/upload-artifact
    tag: "v4"
  - name: azure/setup-helm
    tag: "v4"
  - name: docker/build-push-action
    tag: "v6"
  - name: docker/login-action
    tag: "v3"
  - name: docker/metadata-action
    tag: "v5"
  - name: docker/setup-buildx-action
    tag: "v3"
  - name: docker/setup-qemu-action
    tag: "v3"
  - name: google-github-actions/auth
    tag: "v2"
  - name: google-github-actions/setup-gcloud
    tag: "v2"
  - name: goreleaser/goreleaser-action
    tag: "v6"
  - name: helm/chart-testing-action
    tag: "v2.6.1"
  - name: helm/kind-action
    tag: "v1.10.0"
  - name: rajatjindal/krew-release-bot
    tag: "v0.0.46"
    hash: "df3eb197549e3568be8b4767eec31c5e8e8e6ad8"
  - name: tj-actions/changed-files
    tag: "v44.4.0"
    hash: "a29e8b565651ce417abb5db7164b4a2ad8b6155c"
deny:
  - name: actions/create-release
    reason: archived
  - name: actions/upload-release-asset
    reason: archived
